### ISSUE TITLE
FloatField needs to support sqlite driver

### ISSUE THREAD

**Issue by goldcaddy77** [goldcaddy77/warthog#134]
Run the following:

```
 cd examples/1-simple-model && DEBUG=* yarn ts-node tools/generate.ts
```

and we get:

```
  warthog:error DataTypeNotSupportedError: Data type "float8" in "User.rating" is not supported by "sqlite" database.
  warthog:error     at new DataTypeNotSupportedError (/Users/caddy/code/goldcaddy77/warthog/src/error/DataTypeNotSupportedError.ts:9:9)
  warthog:error     at /Users/caddy/code/goldcaddy77/warthog/src/metadata-builder/EntityMetadataValidator.ts:83:27
  warthog:error     at Array.forEach (<anonymous>)
  warthog:error     at EntityMetadataValidator.validate (/Users/caddy/code/goldcaddy77/warthog/src/metadata-builder/EntityMetadataValidator.ts:80:36)
  warthog:error     at /Users/caddy/code/goldcaddy77/warthog/src/metadata-builder/EntityMetadataValidator.ts:44:56
  warthog:error     at Array.forEach (<anonymous>)
  warthog:error     at EntityMetadataValidator.validateMany (/Users/caddy/code/goldcaddy77/warthog/src/metadata-builder/EntityMetadataValidator.ts:44:25)
  warthog:error     at Connection.buildMetadatas (/Users/caddy/code/goldcaddy77/warthog/src/connection/Connection.ts:505:33)
  warthog:error     at Connection.<anonymous> (/Users/caddy/code/goldcaddy77/warthog/src/connection/Connection.ts:189:18)
  warthog:error     at step (/Users/caddy/code/goldcaddy77/warthog/node_modules/tslib/tslib.js:133:27) +0ms
```

**Comment by goldcaddy77** [comment]
Nor does JSONB:

```
  warthog:error DataTypeNotSupportedError: Data type "jsonb" in "User.jsonField" is not supported by "sqlite" database.
```

**Comment by goldcaddy77** [comment]
Fixed here: https://github.com/goldcaddy77/warthog/pull/151
