### ISSUE TITLE
apollo-client and __typename

### ISSUE THREAD

**Issue by diegonc** [goldcaddy77/warthog#354]
`apollo-client` wants to bring a `__typename` field which is not in the source code of the query. `warthog` complains that the column is not present, which is true for the database nor the model have such property.

I tried adding an apiOnly constant field

```
@Model({db: {name: 'work_effort_parties'}})
@Index(["workEffort", "party"], {unique: true})
export class WorkEffortParty extends BaseModel {
  @StringField({apiOnly: true})
  __typename: string = "WorkEffortParty"
```
but then the schema generation failed with the following message:
```
{ Error: Generating schema error
    at Function.<anonymous> (/home/diegonc/dev/test/quasar/wireframe-api/node_modules/type-graphql/dist/schema/schema-generator.js:20:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/diegonc/dev/test/quasar/wireframe-api/node_modules/tslib/tslib.js:110:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  details:
   [ { GraphQLError: Name "__typename" must not begin with "__", which is reserved by GraphQL introspection.
```
adding it as a `@FieldResolver` also triggers the error above

BTW, this apollo feature can be disabled like [here](https://www.apollographql.com/docs/react/caching/cache-configuration/#configuring-the-cache) but reduces the functionality of the cache

**Comment by goldcaddy77** [comment]
@diegonc `__typename` should automatically be added. You don’t have to specify it explicitly in your schema.

**Comment by diegonc** [comment]
I'm getting the following error as a result of querying the graphql server

```json
{
   "errors":[
      {
         "message":"column workeffort.__typename does not exist",
         "locations":[
            {
               "line":2,
               "column":3
            }
         ],
         "path":[
            "workEfforts"
         ],
         "extensions":{
            "code":"INTERNAL_SERVER_ERROR",
            "exception":{
               "message":"column workeffort.__typename does not exist",
               "name":"QueryFailedError",
               "length":120,
               "severity":"ERROR",
               "code":"42703",
               "position":"318",
               "file":"parse_relation.c",
               "line":"3293",
               "routine":"errorMissingColumn",
               "query":"SELECT \"workeffort\".\"id\" AS \"workeffort_id\", \"workeffort\".\"work_effort_name\" AS \"workeffort_work_effort_name\", \"workeffort\".\"purpose\" AS \"workeffort_purpose\", \"workeffort\".\"estimated_start_date\" AS \"workeffort_estimated_start_date\", \"workeffort\".\"estimated_completion_date\" AS \"workeffort_estimated_completion_date\", workeffort.__typename FROM \"work_efforts\" \"workeffort\" WHERE \"workeffort\".\"deleted_at\" IS NULL LIMIT 50",
               "parameters":[

               ],
               "stacktrace":[
                  "QueryFailedError: column workeffort.__typename does not exist",
                  "    at new QueryFailedError (/home/diegonc/dev/test/quasar/wireframe-api/src/error/QueryFailedError.ts:9:9)",
                  "    at Query.callback (/home/diegonc/dev/test/quasar/wireframe-api/src/driver/postgres/PostgresQueryRunner.ts:178:30)",
                  "    at Query.handleError (/home/diegonc/dev/test/quasar/wireframe-api/node_modules/pg/lib/query.js:145:17)",
                  "    at Connection.connectedErrorMessageHandler (/home/diegonc/dev/test/quasar/wireframe-api/node_modules/pg/lib/client.js:214:17)",
                  "    at Connection.emit (events.js:189:13)",
                  "    at Socket.<anonymous> (/home/diegonc/dev/test/quasar/wireframe-api/node_modules/pg/lib/connection.js:134:12)",
                  "    at Socket.emit (events.js:189:13)",
                  "    at addChunk (_stream_readable.js:284:12)",
                  "    at readableAddChunk (_stream_readable.js:265:11)",
                  "    at Socket.Readable.push (_stream_readable.js:220:10)"
               ]
            }
         }
      }
   ],
   "data":null
}
```

**Comment by goldcaddy77** [comment]
Can you show me the GQL you're sending from the client?  From what I've read, `__typename` is something that Apollo Client automatically injects: https://github.com/apollographql/apollo-client/issues/1913 .   You shouldn't have to ask for it in your GQL.

**Comment by diegonc** [comment]
I'm using a `vue-apollo` smart query defined as
```javascript
apollo: {
    workEfforts: {
      query: gql`
        query WorkEfforts {
          workEfforts {
            id
            workEffortName
            purpose
            estimatedStartDate
            estimatedCompletionDate
            parties {
              role
              party {
                id
                commonName
              }
            }
          }
        }
      `
    }
  },
```

But Developer Tools shows the following query is finally sent to the network

```
{"operationName":"WorkEfforts","variables":{},"query":"query WorkEfforts {\n  workEfforts {\n    id\n    workEffortName\n    purpose\n    estimatedStartDate\n    estimatedCompletionDate\n    parties {\n      role\n      party {\n        id\n        commonName\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}
```

__typename is added by apollo-client, otherwise the query is the same

**Comment by goldcaddy77** [comment]
Oh I think I know what's going on.  Will take a look now.

**Comment by goldcaddy77** [comment]
Are you using the `Fields` decorator?  If so, I have a fix here: https://github.com/goldcaddy77/warthog/pull/355

**Comment by goldcaddy77** [comment]
I've merged this, please bump to the latest version and let me know if it's working.

**Comment by diegonc** [comment]
The dependency was bumped to warthog@latest (2.9.1) and now the query works fine. Thanks!
